var a={
    "skillSummaries": [
        {
            "businessUnitId": "4599436",
            "businessUnitName": "HENNY PENNY CORPORATION",
            "abandonCount": "0",
            "abandonRate": "0",
            "agentsAcw": "0",
            "agentsAvailable": "0",
            "agentsIdle": "0",
            "agentsLoggedIn": "0",
            "agentsUnavailable": "0",
            "agentsWorking": "0",
            "averageHandleTime": "0",
            "averageInqueueTime": "0",
            "averageSpeedToAnswer": "0",
            "averageTalkTime": "0",
            "averageWrapTime": "0",
            "campaignId": "4618251",
            "campaignName": "Admin",
            "contactsActive": "0",
            "contactsHandled": "0",
            "contactsOffered": "46",
            "contactsQueued": "0",
            "contactsOutOfSLA": "0",
            "contactsWithinSLA": "0",
            "holdTime": "0",
            "isOutbound": "False",
            "longestQueueDur": "0",
            "mediaTypeId": "4",
            "mediaTypeName": "Phone Call",
            "queueCount": "0",
            "serviceLevel": "100",
            "skillName": "PreQueue-NO AGENT",
            "skillId": "10460413",
            "serviceLevelGoal": "90",
            "serviceLevelThreshold": "30",
            "totalContactTime": "846",
            "dials": "0",
            "connects": "0",
            "connectsAHT": "0.00",
            "rightPartyConnects": "0",
            "rightPartyConnectsAHT": "0.00"
        },
        {
            "businessUnitId": "4599436",
            "businessUnitName": "HENNY PENNY CORPORATION",
            "abandonCount": "3",
            "abandonRate": "27",
            "agentsAcw": "0",
            "agentsAvailable": "0",
            "agentsIdle": "0",
            "agentsLoggedIn": "0",
            "agentsUnavailable": "0",
            "agentsWorking": "0",
            "averageHandleTime": "64",
            "averageInqueueTime": "60",
            "averageSpeedToAnswer": "23",
            "averageTalkTime": "64",
            "averageWrapTime": "0",
            "campaignId": "4618252",
            "campaignName": "Customer Service",
            "contactsActive": "0",
            "contactsHandled": "8",
            "contactsOffered": "12",
            "contactsQueued": "11",
            "contactsOutOfSLA": "2",
            "contactsWithinSLA": "7",
            "holdTime": "16",
            "isOutbound": "False",
            "longestQueueDur": "0",
            "mediaTypeId": "4",
            "mediaTypeName": "Phone Call",
            "queueCount": "0",
            "serviceLevel": "78",
            "skillName": "Customer Service IB",
            "skillId": "10460414",
            "serviceLevelGoal": "90",
            "serviceLevelThreshold": "30",
            "totalContactTime": "1992",
            "dials": "0",
            "connects": "8",
            "connectsAHT": "0.07",
            "rightPartyConnects": "0",
            "rightPartyConnectsAHT": "0.00"
        },
        {
            "businessUnitId": "4599436",
            "businessUnitName": "HENNY PENNY CORPORATION",
            "abandonCount": "0",
            "abandonRate": "0",
            "agentsAcw": "0",
            "agentsAvailable": "0",
            "agentsIdle": "0",
            "agentsLoggedIn": "0",
            "agentsUnavailable": "0",
            "agentsWorking": "0",
            "averageHandleTime": "0",
            "averageInqueueTime": "0",
            "averageSpeedToAnswer": "0",
            "averageTalkTime": "0",
            "averageWrapTime": "0",
            "campaignId": "4618252",
            "campaignName": "Customer Service",
            "contactsActive": "0",
            "contactsHandled": "0",
            "contactsOffered": "0",
            "contactsQueued": "0",
            "contactsOutOfSLA": "0",
            "contactsWithinSLA": "0",
            "holdTime": "0",
            "isOutbound": "False",
            "longestQueueDur": "0",
            "mediaTypeId": "4",
            "mediaTypeName": "Phone Call",
            "queueCount": "0",
            "serviceLevel": "100",
            "skillName": "Welcome Agents IB",
            "skillId": "10460415",
            "serviceLevelGoal": "90",
            "serviceLevelThreshold": "30",
            "totalContactTime": "0",
            "dials": "0",
            "connects": "0",
            "connectsAHT": "0.00",
            "rightPartyConnects": "0",
            "rightPartyConnectsAHT": "0.00"
        },
        {
            "businessUnitId": "4599436",
            "businessUnitName": "HENNY PENNY CORPORATION",
            "abandonCount": "34",
            "abandonRate": "28",
            "agentsAcw": "0",
            "agentsAvailable": "0",
            "agentsIdle": "0",
            "agentsLoggedIn": "0",
            "agentsUnavailable": "0",
            "agentsWorking": "0",
            "averageHandleTime": "350",
            "averageInqueueTime": "549",
            "averageSpeedToAnswer": "692",
            "averageTalkTime": "328",
            "averageWrapTime": "22",
            "campaignId": "4618253",
            "campaignName": "Technical Support",
            "contactsActive": "0",
            "contactsHandled": "87",
            "contactsOffered": "121",
            "contactsQueued": "121",
            "contactsOutOfSLA": "112",
            "contactsWithinSLA": "9",
            "holdTime": "0",
            "isOutbound": "False",
            "longestQueueDur": "0",
            "mediaTypeId": "4",
            "mediaTypeName": "Phone Call",
            "queueCount": "0",
            "serviceLevel": "7",
            "skillName": "End User IB",
            "skillId": "10460416",
            "serviceLevelGoal": "80",
            "serviceLevelThreshold": "180",
            "totalContactTime": "96173",
            "dials": "0",
            "connects": "91",
            "connectsAHT": "0.31",
            "rightPartyConnects": "0",
            "rightPartyConnectsAHT": "0.00"
        },
        {
            "businessUnitId": "4599436",
            "businessUnitName": "HENNY PENNY CORPORATION",
            "abandonCount": "34",
            "abandonRate": "20",
            "agentsAcw": "0",
            "agentsAvailable": "0",
            "agentsIdle": "0",
            "agentsLoggedIn": "0",
            "agentsUnavailable": "0",
            "agentsWorking": "0",
            "averageHandleTime": "376",
            "averageInqueueTime": "551",
            "averageSpeedToAnswer": "617",
            "averageTalkTime": "362",
            "averageWrapTime": "13",
            "campaignId": "4618253",
            "campaignName": "Technical Support",
            "contactsActive": "0",
            "contactsHandled": "134",
            "contactsOffered": "168",
            "contactsQueued": "168",
            "contactsOutOfSLA": "100",
            "contactsWithinSLA": "68",
            "holdTime": "0",
            "isOutbound": "False",
            "longestQueueDur": "0",
            "mediaTypeId": "4",
            "mediaTypeName": "Phone Call",
            "queueCount": "0",
            "serviceLevel": "40",
            "skillName": "Service Tech IB",
            "skillId": "10460418",
            "serviceLevelGoal": "80",
            "serviceLevelThreshold": "480",
            "totalContactTime": "142540",
            "dials": "0",
            "connects": "135",
            "connectsAHT": "0.36",
            "rightPartyConnects": "0",
            "rightPartyConnectsAHT": "0.00"
        },
        {
            "businessUnitId": "4599436",
            "businessUnitName": "HENNY PENNY CORPORATION",
            "abandonCount": "0",
            "abandonRate": "0",
            "agentsAcw": "0",
            "agentsAvailable": "0",
            "agentsIdle": "0",
            "agentsLoggedIn": "0",
            "agentsUnavailable": "0",
            "agentsWorking": "0",
            "averageHandleTime": "0",
            "averageInqueueTime": "0",
            "averageSpeedToAnswer": "0",
            "averageTalkTime": "0",
            "averageWrapTime": "0",
            "campaignId": "4618253",
            "campaignName": "Technical Support",
            "contactsActive": "0",
            "contactsHandled": "0",
            "contactsOffered": "0",
            "contactsQueued": "0",
            "contactsOutOfSLA": "0",
            "contactsWithinSLA": "0",
            "holdTime": "0",
            "isOutbound": "False",
            "longestQueueDur": "0",
            "mediaTypeId": "4",
            "mediaTypeName": "Phone Call",
            "queueCount": "0",
            "serviceLevel": "100",
            "skillName": "Spanish IB",
            "skillId": "10460420",
            "serviceLevelGoal": "90",
            "serviceLevelThreshold": "30",
            "totalContactTime": "0",
            "dials": "0",
            "connects": "0",
            "connectsAHT": "0.00",
            "rightPartyConnects": "0",
            "rightPartyConnectsAHT": "0.00"
        },
        {
            "businessUnitId": "4599436",
            "businessUnitName": "HENNY PENNY CORPORATION",
            "abandonCount": "0",
            "abandonRate": "0",
            "agentsAcw": "0",
            "agentsAvailable": "0",
            "agentsIdle": "0",
            "agentsLoggedIn": "0",
            "agentsUnavailable": "0",
            "agentsWorking": "0",
            "averageHandleTime": "0",
            "averageInqueueTime": "0",
            "averageSpeedToAnswer": "0",
            "averageTalkTime": "0",
            "averageWrapTime": "0",
            "campaignId": "4618253",
            "campaignName": "Technical Support",
            "contactsActive": "0",
            "contactsHandled": "0",
            "contactsOffered": "0",
            "contactsQueued": "0",
            "contactsOutOfSLA": "0",
            "contactsWithinSLA": "0",
            "holdTime": "0",
            "isOutbound": "False",
            "longestQueueDur": "0",
            "mediaTypeId": "4",
            "mediaTypeName": "Phone Call",
            "queueCount": "0",
            "serviceLevel": "100",
            "skillName": "Escalation IB",
            "skillId": "10460421",
            "serviceLevelGoal": "90",
            "serviceLevelThreshold": "30",
            "totalContactTime": "0",
            "dials": "0",
            "connects": "0",
            "connectsAHT": "0.00",
            "rightPartyConnects": "0",
            "rightPartyConnectsAHT": "0.00"
        },
        {
            "businessUnitId": "4599436",
            "businessUnitName": "HENNY PENNY CORPORATION",
            "abandonCount": "0",
            "abandonRate": "0",
            "agentsAcw": "0",
            "agentsAvailable": "0",
            "agentsIdle": "0",
            "agentsLoggedIn": "0",
            "agentsUnavailable": "0",
            "agentsWorking": "0",
            "averageHandleTime": "0",
            "averageInqueueTime": "0",
            "averageSpeedToAnswer": "0",
            "averageTalkTime": "0",
            "averageWrapTime": "0",
            "campaignId": "4618253",
            "campaignName": "Technical Support",
            "contactsActive": "0",
            "contactsHandled": "0",
            "contactsOffered": "0",
            "contactsQueued": "0",
            "contactsOutOfSLA": "0",
            "contactsWithinSLA": "0",
            "holdTime": "0",
            "isOutbound": "False",
            "longestQueueDur": "0",
            "mediaTypeId": "4",
            "mediaTypeName": "Phone Call",
            "queueCount": "0",
            "serviceLevel": "100",
            "skillName": "Distributor IB",
            "skillId": "10460422",
            "serviceLevelGoal": "80",
            "serviceLevelThreshold": "300",
            "totalContactTime": "0",
            "dials": "0",
            "connects": "0",
            "connectsAHT": "0.00",
            "rightPartyConnects": "0",
            "rightPartyConnectsAHT": "0.00"
        },
        {
            "businessUnitId": "4599436",
            "businessUnitName": "HENNY PENNY CORPORATION",
            "abandonCount": "4",
            "abandonRate": "31",
            "agentsAcw": "0",
            "agentsAvailable": "0",
            "agentsIdle": "0",
            "agentsLoggedIn": "0",
            "agentsUnavailable": "0",
            "agentsWorking": "0",
            "averageHandleTime": "564",
            "averageInqueueTime": "293",
            "averageSpeedToAnswer": "354",
            "averageTalkTime": "540",
            "averageWrapTime": "24",
            "campaignId": "4618253",
            "campaignName": "Technical Support",
            "contactsActive": "0",
            "contactsHandled": "9",
            "contactsOffered": "13",
            "contactsQueued": "13",
            "contactsOutOfSLA": "11",
            "contactsWithinSLA": "2",
            "holdTime": "0",
            "isOutbound": "False",
            "longestQueueDur": "0",
            "mediaTypeId": "4",
            "mediaTypeName": "Phone Call",
            "queueCount": "0",
            "serviceLevel": "15",
            "skillName": "Combined IB",
            "skillId": "10460423",
            "serviceLevelGoal": "90",
            "serviceLevelThreshold": "30",
            "totalContactTime": "8680",
            "dials": "0",
            "connects": "9",
            "connectsAHT": "0.54",
            "rightPartyConnects": "0",
            "rightPartyConnectsAHT": "0.00"
        },
        {
            "businessUnitId": "4599436",
            "businessUnitName": "HENNY PENNY CORPORATION",
            "abandonCount": "0",
            "abandonRate": "0",
            "agentsAcw": "0",
            "agentsAvailable": "0",
            "agentsIdle": "0",
            "agentsLoggedIn": "0",
            "agentsUnavailable": "0",
            "agentsWorking": "0",
            "averageHandleTime": "512",
            "averageInqueueTime": "0",
            "averageSpeedToAnswer": "0",
            "averageTalkTime": "482",
            "averageWrapTime": "29",
            "campaignId": "4618253",
            "campaignName": "Technical Support",
            "contactsActive": "0",
            "contactsHandled": "11",
            "contactsOffered": "11",
            "contactsQueued": "0",
            "contactsOutOfSLA": "0",
            "contactsWithinSLA": "0",
            "holdTime": "0",
            "isOutbound": "True",
            "longestQueueDur": "0",
            "mediaTypeId": "4",
            "mediaTypeName": "Phone Call",
            "queueCount": "0",
            "serviceLevel": "100",
            "skillName": "Tech Support OB",
            "skillId": "10460424",
            "serviceLevelGoal": "90",
            "serviceLevelThreshold": "30",
            "totalContactTime": "5311",
            "dials": "12",
            "connects": "11",
            "connectsAHT": "0.48",
            "rightPartyConnects": "0",
            "rightPartyConnectsAHT": "0.00"
        },
        {
            "businessUnitId": "4599436",
            "businessUnitName": "HENNY PENNY CORPORATION",
            "abandonCount": "0",
            "abandonRate": "0",
            "agentsAcw": "0",
            "agentsAvailable": "0",
            "agentsIdle": "0",
            "agentsLoggedIn": "0",
            "agentsUnavailable": "0",
            "agentsWorking": "0",
            "averageHandleTime": "3",
            "averageInqueueTime": "0",
            "averageSpeedToAnswer": "0",
            "averageTalkTime": "3",
            "averageWrapTime": "0",
            "campaignId": "4618252",
            "campaignName": "Customer Service",
            "contactsActive": "0",
            "contactsHandled": "2",
            "contactsOffered": "2",
            "contactsQueued": "0",
            "contactsOutOfSLA": "0",
            "contactsWithinSLA": "0",
            "holdTime": "0",
            "isOutbound": "True",
            "longestQueueDur": "0",
            "mediaTypeId": "4",
            "mediaTypeName": "Phone Call",
            "queueCount": "0",
            "serviceLevel": "100",
            "skillName": "Customer Service OB",
            "skillId": "10460425",
            "serviceLevelGoal": "90",
            "serviceLevelThreshold": "30",
            "totalContactTime": "309",
            "dials": "2",
            "connects": "2",
            "connectsAHT": "0.01",
            "rightPartyConnects": "0",
            "rightPartyConnectsAHT": "0.00"
        },
        {
            "businessUnitId": "4599436",
            "businessUnitName": "HENNY PENNY CORPORATION",
            "abandonCount": "0",
            "abandonRate": "0",
            "agentsAcw": "0",
            "agentsAvailable": "0",
            "agentsIdle": "0",
            "agentsLoggedIn": "0",
            "agentsUnavailable": "0",
            "agentsWorking": "0",
            "averageHandleTime": "0",
            "averageInqueueTime": "0",
            "averageSpeedToAnswer": "0",
            "averageTalkTime": "0",
            "averageWrapTime": "0",
            "campaignId": "4618252",
            "campaignName": "Customer Service",
            "contactsActive": "0",
            "contactsHandled": "0",
            "contactsOffered": "0",
            "contactsQueued": "0",
            "contactsOutOfSLA": "0",
            "contactsWithinSLA": "0",
            "holdTime": "0",
            "isOutbound": "False",
            "longestQueueDur": "0",
            "mediaTypeId": "5",
            "mediaTypeName": "Voice Mail",
            "queueCount": "0",
            "serviceLevel": "100",
            "skillName": "Customer Service VM",
            "skillId": "10460426",
            "serviceLevelGoal": "90",
            "serviceLevelThreshold": "30",
            "totalContactTime": "0",
            "dials": "0",
            "connects": "0",
            "connectsAHT": "0.00",
            "rightPartyConnects": "0",
            "rightPartyConnectsAHT": "0.00"
        },
        {
            "businessUnitId": "4599436",
            "businessUnitName": "HENNY PENNY CORPORATION",
            "abandonCount": "0",
            "abandonRate": "0",
            "agentsAcw": "0",
            "agentsAvailable": "0",
            "agentsIdle": "0",
            "agentsLoggedIn": "0",
            "agentsUnavailable": "0",
            "agentsWorking": "0",
            "averageHandleTime": "0",
            "averageInqueueTime": "0",
            "averageSpeedToAnswer": "0",
            "averageTalkTime": "0",
            "averageWrapTime": "0",
            "campaignId": "4618253",
            "campaignName": "Technical Support",
            "contactsActive": "0",
            "contactsHandled": "0",
            "contactsOffered": "0",
            "contactsQueued": "0",
            "contactsOutOfSLA": "0",
            "contactsWithinSLA": "0",
            "holdTime": "0",
            "isOutbound": "False",
            "longestQueueDur": "41169",
            "mediaTypeId": "5",
            "mediaTypeName": "Voice Mail",
            "queueCount": "5",
            "serviceLevel": "100",
            "skillName": "General VM",
            "skillId": "10460427",
            "serviceLevelGoal": "90",
            "serviceLevelThreshold": "30",
            "totalContactTime": "0",
            "dials": "0",
            "connects": "0",
            "connectsAHT": "0.00",
            "rightPartyConnects": "0",
            "rightPartyConnectsAHT": "0.00"
        },
        {
            "businessUnitId": "4599436",
            "businessUnitName": "HENNY PENNY CORPORATION",
            "abandonCount": "0",
            "abandonRate": "0",
            "agentsAcw": "0",
            "agentsAvailable": "0",
            "agentsIdle": "0",
            "agentsLoggedIn": "0",
            "agentsUnavailable": "0",
            "agentsWorking": "0",
            "averageHandleTime": "820",
            "averageInqueueTime": "57",
            "averageSpeedToAnswer": "57",
            "averageTalkTime": "746",
            "averageWrapTime": "74",
            "campaignId": "4618253",
            "campaignName": "Technical Support",
            "contactsActive": "0",
            "contactsHandled": "5",
            "contactsOffered": "5",
            "contactsQueued": "5",
            "contactsOutOfSLA": "3",
            "contactsWithinSLA": "2",
            "holdTime": "0",
            "isOutbound": "False",
            "longestQueueDur": "0",
            "mediaTypeId": "3",
            "mediaTypeName": "Chat",
            "queueCount": "0",
            "serviceLevel": "40",
            "skillName": "End User Chat",
            "skillId": "10460428",
            "serviceLevelGoal": "90",
            "serviceLevelThreshold": "30",
            "totalContactTime": "4019",
            "dials": "0",
            "connects": "5",
            "connectsAHT": "0.75",
            "rightPartyConnects": "0",
            "rightPartyConnectsAHT": "0.00"
        },
        {
            "businessUnitId": "4599436",
            "businessUnitName": "HENNY PENNY CORPORATION",
            "abandonCount": "5",
            "abandonRate": "100",
            "agentsAcw": "0",
            "agentsAvailable": "0",
            "agentsIdle": "0",
            "agentsLoggedIn": "0",
            "agentsUnavailable": "0",
            "agentsWorking": "0",
            "averageHandleTime": "0",
            "averageInqueueTime": "330",
            "averageSpeedToAnswer": "0",
            "averageTalkTime": "0",
            "averageWrapTime": "0",
            "campaignId": "4618253",
            "campaignName": "Technical Support",
            "contactsActive": "0",
            "contactsHandled": "0",
            "contactsOffered": "14",
            "contactsQueued": "5",
            "contactsOutOfSLA": "5",
            "contactsWithinSLA": "0",
            "holdTime": "0",
            "isOutbound": "False",
            "longestQueueDur": "0",
            "mediaTypeId": "3",
            "mediaTypeName": "Chat",
            "queueCount": "0",
            "serviceLevel": "0",
            "skillName": "Service Tech Chat",
            "skillId": "10460429",
            "serviceLevelGoal": "90",
            "serviceLevelThreshold": "30",
            "totalContactTime": "1659",
            "dials": "0",
            "connects": "0",
            "connectsAHT": "0.00",
            "rightPartyConnects": "0",
            "rightPartyConnectsAHT": "0.00"
        },
        {
            "businessUnitId": "4599436",
            "businessUnitName": "HENNY PENNY CORPORATION",
            "abandonCount": "0",
            "abandonRate": "0",
            "agentsAcw": "0",
            "agentsAvailable": "0",
            "agentsIdle": "0",
            "agentsLoggedIn": "0",
            "agentsUnavailable": "0",
            "agentsWorking": "0",
            "averageHandleTime": "0",
            "averageInqueueTime": "0",
            "averageSpeedToAnswer": "0",
            "averageTalkTime": "0",
            "averageWrapTime": "0",
            "campaignId": "4618253",
            "campaignName": "Technical Support",
            "contactsActive": "0",
            "contactsHandled": "0",
            "contactsOffered": "0",
            "contactsQueued": "0",
            "contactsOutOfSLA": "0",
            "contactsWithinSLA": "0",
            "holdTime": "0",
            "isOutbound": "False",
            "longestQueueDur": "0",
            "mediaTypeId": "7",
            "mediaTypeName": "SMS",
            "queueCount": "0",
            "serviceLevel": "100",
            "skillName": "End User Text",
            "skillId": "10460430",
            "serviceLevelGoal": "90",
            "serviceLevelThreshold": "30",
            "totalContactTime": "0",
            "dials": "0",
            "connects": "0",
            "connectsAHT": "0.00",
            "rightPartyConnects": "0",
            "rightPartyConnectsAHT": "0.00"
        },
        {
            "businessUnitId": "4599436",
            "businessUnitName": "HENNY PENNY CORPORATION",
            "abandonCount": "0",
            "abandonRate": "0",
            "agentsAcw": "0",
            "agentsAvailable": "0",
            "agentsIdle": "0",
            "agentsLoggedIn": "0",
            "agentsUnavailable": "0",
            "agentsWorking": "0",
            "averageHandleTime": "0",
            "averageInqueueTime": "0",
            "averageSpeedToAnswer": "0",
            "averageTalkTime": "0",
            "averageWrapTime": "0",
            "campaignId": "4618253",
            "campaignName": "Technical Support",
            "contactsActive": "0",
            "contactsHandled": "0",
            "contactsOffered": "0",
            "contactsQueued": "0",
            "contactsOutOfSLA": "0",
            "contactsWithinSLA": "0",
            "holdTime": "0",
            "isOutbound": "False",
            "longestQueueDur": "0",
            "mediaTypeId": "7",
            "mediaTypeName": "SMS",
            "queueCount": "0",
            "serviceLevel": "100",
            "skillName": "Service Tech Text",
            "skillId": "10460431",
            "serviceLevelGoal": "90",
            "serviceLevelThreshold": "30",
            "totalContactTime": "0",
            "dials": "0",
            "connects": "0",
            "connectsAHT": "0.00",
            "rightPartyConnects": "0",
            "rightPartyConnectsAHT": "0.00"
        },
        {
            "businessUnitId": "4599436",
            "businessUnitName": "HENNY PENNY CORPORATION",
            "abandonCount": "0",
            "abandonRate": "0",
            "agentsAcw": "0",
            "agentsAvailable": "0",
            "agentsIdle": "0",
            "agentsLoggedIn": "0",
            "agentsUnavailable": "0",
            "agentsWorking": "0",
            "averageHandleTime": "901",
            "averageInqueueTime": "2265",
            "averageSpeedToAnswer": "2265",
            "averageTalkTime": "874",
            "averageWrapTime": "27",
            "campaignId": "4618253",
            "campaignName": "Technical Support",
            "contactsActive": "0",
            "contactsHandled": "24",
            "contactsOffered": "24",
            "contactsQueued": "24",
            "contactsOutOfSLA": "17",
            "contactsWithinSLA": "5",
            "holdTime": "0",
            "isOutbound": "False",
            "longestQueueDur": "11444",
            "mediaTypeId": "1",
            "mediaTypeName": "E-Mail",
            "queueCount": "2",
            "serviceLevel": "23",
            "skillName": "Parts Department Email",
            "skillId": "10460432",
            "serviceLevelGoal": "90",
            "serviceLevelThreshold": "30",
            "totalContactTime": "75352",
            "dials": "0",
            "connects": "25",
            "connectsAHT": "0.84",
            "rightPartyConnects": "0",
            "rightPartyConnectsAHT": "0.00"
        },
        {
            "businessUnitId": "4599436",
            "businessUnitName": "HENNY PENNY CORPORATION",
            "abandonCount": "0",
            "abandonRate": "0",
            "agentsAcw": "0",
            "agentsAvailable": "0",
            "agentsIdle": "0",
            "agentsLoggedIn": "0",
            "agentsUnavailable": "0",
            "agentsWorking": "0",
            "averageHandleTime": "478",
            "averageInqueueTime": "2777",
            "averageSpeedToAnswer": "2777",
            "averageTalkTime": "456",
            "averageWrapTime": "21",
            "campaignId": "4618253",
            "campaignName": "Technical Support",
            "contactsActive": "0",
            "contactsHandled": "18",
            "contactsOffered": "18",
            "contactsQueued": "18",
            "contactsOutOfSLA": "12",
            "contactsWithinSLA": "5",
            "holdTime": "0",
            "isOutbound": "False",
            "longestQueueDur": "0",
            "mediaTypeId": "1",
            "mediaTypeName": "E-Mail",
            "queueCount": "0",
            "serviceLevel": "29",
            "skillName": "Tech Service Email",
            "skillId": "10460433",
            "serviceLevelGoal": "90",
            "serviceLevelThreshold": "30",
            "totalContactTime": "58201",
            "dials": "0",
            "connects": "18",
            "connectsAHT": "0.46",
            "rightPartyConnects": "0",
            "rightPartyConnectsAHT": "0.00"
        },
        {
            "businessUnitId": "4599436",
            "businessUnitName": "HENNY PENNY CORPORATION",
            "abandonCount": "0",
            "abandonRate": "0",
            "agentsAcw": "0",
            "agentsAvailable": "0",
            "agentsIdle": "0",
            "agentsLoggedIn": "0",
            "agentsUnavailable": "0",
            "agentsWorking": "0",
            "averageHandleTime": "478",
            "averageInqueueTime": "2777",
            "averageSpeedToAnswer": "2777",
            "averageTalkTime": "456",
            "averageWrapTime": "21",
            "campaignId": "4618253",
            "campaignName": "Technical Support",
            "contactsActive": "0",
            "contactsHandled": "18",
            "contactsOffered": "18",
            "contactsQueued": "18",
            "contactsOutOfSLA": "12",
            "contactsWithinSLA": "5",
            "holdTime": "0",
            "isOutbound": "False",
            "longestQueueDur": "7060",
            "mediaTypeId": "1",
            "mediaTypeName": "E-Mail",
            "queueCount": "1",
            "serviceLevel": "29",
            "skillName": "Tech Service Email",
            "skillId": "10460433",
            "serviceLevelGoal": "90",
            "serviceLevelThreshold": "30",
            "totalContactTime": "58201",
            "dials": "0",
            "connects": "18",
            "connectsAHT": "0.46",
            "rightPartyConnects": "0",
            "rightPartyConnectsAHT": "0.00"
        },
        {
            "businessUnitId": "4599436",
            "businessUnitName": "HENNY PENNY CORPORATION",
            "abandonCount": "2",
            "abandonRate": "40",
            "agentsAcw": "0",
            "agentsAvailable": "0",
            "agentsIdle": "0",
            "agentsLoggedIn": "0",
            "agentsUnavailable": "0",
            "agentsWorking": "0",
            "averageHandleTime": "234",
            "averageInqueueTime": "37",
            "averageSpeedToAnswer": "20",
            "averageTalkTime": "219",
            "averageWrapTime": "15",
            "campaignId": "4618254",
            "campaignName": "IT Service Desk",
            "contactsActive": "0",
            "contactsHandled": "3",
            "contactsOffered": "6",
            "contactsQueued": "5",
            "contactsOutOfSLA": "3",
            "contactsWithinSLA": "2",
            "holdTime": "0",
            "isOutbound": "False",
            "longestQueueDur": "0",
            "mediaTypeId": "4",
            "mediaTypeName": "Phone Call",
            "queueCount": "0",
            "serviceLevel": "40",
            "skillName": "IT Service Desk IB",
            "skillId": "10460435",
            "serviceLevelGoal": "90",
            "serviceLevelThreshold": "30",
            "totalContactTime": "935",
            "dials": "0",
            "connects": "3",
            "connectsAHT": "0.22",
            "rightPartyConnects": "0",
            "rightPartyConnectsAHT": "0.00"
        },
        {
            "businessUnitId": "4599436",
            "businessUnitName": "HENNY PENNY CORPORATION",
            "abandonCount": "0",
            "abandonRate": "0",
            "agentsAcw": "0",
            "agentsAvailable": "0",
            "agentsIdle": "0",
            "agentsLoggedIn": "0",
            "agentsUnavailable": "0",
            "agentsWorking": "0",
            "averageHandleTime": "293",
            "averageInqueueTime": "0",
            "averageSpeedToAnswer": "0",
            "averageTalkTime": "278",
            "averageWrapTime": "15",
            "campaignId": "4618254",
            "campaignName": "IT Service Desk",
            "contactsActive": "0",
            "contactsHandled": "6",
            "contactsOffered": "6",
            "contactsQueued": "0",
            "contactsOutOfSLA": "0",
            "contactsWithinSLA": "0",
            "holdTime": "0",
            "isOutbound": "True",
            "longestQueueDur": "0",
            "mediaTypeId": "4",
            "mediaTypeName": "Phone Call",
            "queueCount": "0",
            "serviceLevel": "100",
            "skillName": "IT Service Desk OB",
            "skillId": "10460436",
            "serviceLevelGoal": "90",
            "serviceLevelThreshold": "30",
            "totalContactTime": "1668",
            "dials": "6",
            "connects": "6",
            "connectsAHT": "0.28",
            "rightPartyConnects": "0",
            "rightPartyConnectsAHT": "0.00"
        },
        {
            "businessUnitId": "4599436",
            "businessUnitName": "HENNY PENNY CORPORATION",
            "abandonCount": "0",
            "abandonRate": "0",
            "agentsAcw": "0",
            "agentsAvailable": "0",
            "agentsIdle": "0",
            "agentsLoggedIn": "0",
            "agentsUnavailable": "0",
            "agentsWorking": "0",
            "averageHandleTime": "0",
            "averageInqueueTime": "0",
            "averageSpeedToAnswer": "0",
            "averageTalkTime": "0",
            "averageWrapTime": "0",
            "campaignId": "4618254",
            "campaignName": "IT Service Desk",
            "contactsActive": "0",
            "contactsHandled": "0",
            "contactsOffered": "0",
            "contactsQueued": "0",
            "contactsOutOfSLA": "0",
            "contactsWithinSLA": "0",
            "holdTime": "0",
            "isOutbound": "False",
            "longestQueueDur": "0",
            "mediaTypeId": "5",
            "mediaTypeName": "Voice Mail",
            "queueCount": "0",
            "serviceLevel": "100",
            "skillName": "IT Service Desk VM",
            "skillId": "10460437",
            "serviceLevelGoal": "90",
            "serviceLevelThreshold": "30",
            "totalContactTime": "0",
            "dials": "0",
            "connects": "0",
            "connectsAHT": "0.00",
            "rightPartyConnects": "0",
            "rightPartyConnectsAHT": "0.00"
        },
        {
            "businessUnitId": "4599436",
            "businessUnitName": "HENNY PENNY CORPORATION",
            "abandonCount": "0",
            "abandonRate": "0",
            "agentsAcw": "0",
            "agentsAvailable": "0",
            "agentsIdle": "0",
            "agentsLoggedIn": "0",
            "agentsUnavailable": "0",
            "agentsWorking": "0",
            "averageHandleTime": "241",
            "averageInqueueTime": "7512",
            "averageSpeedToAnswer": "7512",
            "averageTalkTime": "241",
            "averageWrapTime": "0",
            "campaignId": "4618253",
            "campaignName": "Technical Support",
            "contactsActive": "0",
            "contactsHandled": "2",
            "contactsOffered": "2",
            "contactsQueued": "2",
            "contactsOutOfSLA": "2",
            "contactsWithinSLA": "0",
            "holdTime": "0",
            "isOutbound": "False",
            "longestQueueDur": "0",
            "mediaTypeId": "6",
            "mediaTypeName": "Work Item",
            "queueCount": "0",
            "serviceLevel": "0",
            "skillName": "Service Tech SMS",
            "skillId": "10483623",
            "serviceLevelGoal": "90",
            "serviceLevelThreshold": "30",
            "totalContactTime": "15506",
            "dials": "0",
            "connects": "1",
            "connectsAHT": "0.48",
            "rightPartyConnects": "0",
            "rightPartyConnectsAHT": "0.00"
        },
        {
            "businessUnitId": "4599436",
            "businessUnitName": "HENNY PENNY CORPORATION",
            "abandonCount": "0",
            "abandonRate": "0",
            "agentsAcw": "0",
            "agentsAvailable": "0",
            "agentsIdle": "0",
            "agentsLoggedIn": "0",
            "agentsUnavailable": "0",
            "agentsWorking": "0",
            "averageHandleTime": "0",
            "averageInqueueTime": "0",
            "averageSpeedToAnswer": "0",
            "averageTalkTime": "0",
            "averageWrapTime": "0",
            "campaignId": "4618251",
            "campaignName": "Admin",
            "contactsActive": "0",
            "contactsHandled": "0",
            "contactsOffered": "0",
            "contactsQueued": "0",
            "contactsOutOfSLA": "0",
            "contactsWithinSLA": "0",
            "holdTime": "0",
            "isOutbound": "False",
            "longestQueueDur": "0",
            "mediaTypeId": "4",
            "mediaTypeName": "Phone Call",
            "queueCount": "0",
            "serviceLevel": "100",
            "skillName": "Test Skill",
            "skillId": "10511855",
            "serviceLevelGoal": "90",
            "serviceLevelThreshold": "30",
            "totalContactTime": "0",
            "dials": "0",
            "connects": "0",
            "connectsAHT": "0.00",
            "rightPartyConnects": "0",
            "rightPartyConnectsAHT": "0.00"
        },
        {
            "businessUnitId": "4599436",
            "businessUnitName": "HENNY PENNY CORPORATION",
            "abandonCount": "0",
            "abandonRate": "0",
            "agentsAcw": "0",
            "agentsAvailable": "0",
            "agentsIdle": "0",
            "agentsLoggedIn": "0",
            "agentsUnavailable": "0",
            "agentsWorking": "0",
            "averageHandleTime": "0",
            "averageInqueueTime": "0",
            "averageSpeedToAnswer": "0",
            "averageTalkTime": "0",
            "averageWrapTime": "0",
            "campaignId": "4618253",
            "campaignName": "Technical Support",
            "contactsActive": "0",
            "contactsHandled": "0",
            "contactsOffered": "0",
            "contactsQueued": "0",
            "contactsOutOfSLA": "0",
            "contactsWithinSLA": "0",
            "holdTime": "0",
            "isOutbound": "True",
            "longestQueueDur": "0",
            "mediaTypeId": "1",
            "mediaTypeName": "E-Mail",
            "queueCount": "0",
            "serviceLevel": "100",
            "skillName": "Service Tech  EMAIL OB",
            "skillId": "10558731",
            "serviceLevelGoal": "90",
            "serviceLevelThreshold": "30",
            "totalContactTime": "0",
            "dials": "0",
            "connects": "0",
            "connectsAHT": "0.00",
            "rightPartyConnects": "0",
            "rightPartyConnectsAHT": "0.00"
        },
        {
            "businessUnitId": "4599436",
            "businessUnitName": "HENNY PENNY CORPORATION",
            "abandonCount": "0",
            "abandonRate": "0",
            "agentsAcw": "0",
            "agentsAvailable": "0",
            "agentsIdle": "0",
            "agentsLoggedIn": "0",
            "agentsUnavailable": "0",
            "agentsWorking": "0",
            "averageHandleTime": "0",
            "averageInqueueTime": "0",
            "averageSpeedToAnswer": "0",
            "averageTalkTime": "0",
            "averageWrapTime": "0",
            "campaignId": "4618251",
            "campaignName": "Admin",
            "contactsActive": "0",
            "contactsHandled": "0",
            "contactsOffered": "0",
            "contactsQueued": "0",
            "contactsOutOfSLA": "0",
            "contactsWithinSLA": "0",
            "holdTime": "0",
            "isOutbound": "False",
            "longestQueueDur": "0",
            "mediaTypeId": "3",
            "mediaTypeName": "Chat",
            "queueCount": "0",
            "serviceLevel": "100",
            "skillName": "Test Chat",
            "skillId": "10558928",
            "serviceLevelGoal": "90",
            "serviceLevelThreshold": "30",
            "totalContactTime": "0",
            "dials": "0",
            "connects": "0",
            "connectsAHT": "0.00",
            "rightPartyConnects": "0",
            "rightPartyConnectsAHT": "0.00"
        },
        {
            "businessUnitId": "4599436",
            "businessUnitName": "HENNY PENNY CORPORATION",
            "abandonCount": "0",
            "abandonRate": "0",
            "agentsAcw": "0",
            "agentsAvailable": "0",
            "agentsIdle": "0",
            "agentsLoggedIn": "0",
            "agentsUnavailable": "0",
            "agentsWorking": "0",
            "averageHandleTime": "0",
            "averageInqueueTime": "0",
            "averageSpeedToAnswer": "0",
            "averageTalkTime": "0",
            "averageWrapTime": "0",
            "campaignId": "4618253",
            "campaignName": "Technical Support",
            "contactsActive": "0",
            "contactsHandled": "0",
            "contactsOffered": "0",
            "contactsQueued": "0",
            "contactsOutOfSLA": "0",
            "contactsWithinSLA": "0",
            "holdTime": "0",
            "isOutbound": "False",
            "longestQueueDur": "0",
            "mediaTypeId": "4",
            "mediaTypeName": "Phone Call",
            "queueCount": "0",
            "serviceLevel": "100",
            "skillName": "Opted for SMS-NO AGENT",
            "skillId": "10558991",
            "serviceLevelGoal": "90",
            "serviceLevelThreshold": "30",
            "totalContactTime": "0",
            "dials": "0",
            "connects": "0",
            "connectsAHT": "0.00",
            "rightPartyConnects": "0",
            "rightPartyConnectsAHT": "0.00"
        },
        {
            "businessUnitId": "4599436",
            "businessUnitName": "HENNY PENNY CORPORATION",
            "abandonCount": "0",
            "abandonRate": "0",
            "agentsAcw": "0",
            "agentsAvailable": "0",
            "agentsIdle": "0",
            "agentsLoggedIn": "0",
            "agentsUnavailable": "0",
            "agentsWorking": "0",
            "averageHandleTime": "0",
            "averageInqueueTime": "0",
            "averageSpeedToAnswer": "0",
            "averageTalkTime": "0",
            "averageWrapTime": "0",
            "campaignId": "4618253",
            "campaignName": "Technical Support",
            "contactsActive": "0",
            "contactsHandled": "0",
            "contactsOffered": "0",
            "contactsQueued": "0",
            "contactsOutOfSLA": "0",
            "contactsWithinSLA": "0",
            "holdTime": "0",
            "isOutbound": "False",
            "longestQueueDur": "0",
            "mediaTypeId": "6",
            "mediaTypeName": "Work Item",
            "queueCount": "0",
            "serviceLevel": "100",
            "skillName": "End User SMS",
            "skillId": "10558996",
            "serviceLevelGoal": "90",
            "serviceLevelThreshold": "30",
            "totalContactTime": "0",
            "dials": "0",
            "connects": "0",
            "connectsAHT": "0.00",
            "rightPartyConnects": "0",
            "rightPartyConnectsAHT": "0.00"
        }
    ]
};

print(a.length());